# Generated by Django 5.2.6 on 2026-05-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_controlsanitario_empresa_insumo_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlsanitario',
            name='estado_enfermedad',
            field=models.CharField(blank=True, default='Tratamiento', max_length=50, null=True),
        ),
    ]
