# Generated by Django 5.2.6 on 2026-05-31 22:18

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('insumos', '0005_controlsanitario_estado_enfermedad'),
        ('lotes', '0003_lote_empresa'),
        ('usuarios', '0006_usuario_empresa_usuario_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnfermedadLote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_enfermedad', models.CharField(max_length=150)),
                ('aves_afectadas', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('En observacion', 'En observación'), ('Controlado', 'Controlado'), ('Finalizado', 'Finalizado')], default='Activo', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_enfermedad', to='empresas.empresa')),
                ('lote', models.ForeignKey(db_column='id_lote', on_delete=django.db.models.deletion.PROTECT, related_name='registros_enfermedad', to='lotes.lote')),
            ],
            options={
                'db_table': 'registro_enfermedad_lote',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='AlertaSanitaria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('Enfermedad', 'Enfermedad'), ('Mortandad', 'Mortandad'), ('Stock', 'Stock')], max_length=30)),
                ('nivel', models.CharField(choices=[('Media', 'Media'), ('Alta', 'Alta'), ('Critica', 'Crítica')], default='Alta', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('causa', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad_afectada', models.PositiveIntegerField(blank=True, null=True)),
                ('porcentaje_afectado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_detectado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('umbral', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendida', 'Atendida'), ('Resuelta', 'Resuelta')], default='Pendiente', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_sanitarias_atendidas', to='usuarios.usuario')),
                ('empresa', models.ForeignKey(blank=True, db_column='empresa_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_sanitarias', to='empresas.empresa')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_sanitarias', to='insumos.insumo')),
                ('lote', models.ForeignKey(blank=True, db_column='id_lote', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alertas_sanitarias', to='lotes.lote')),
                ('registro_enfermedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_generadas', to='sanitario.registroenfermedadlote')),
            ],
            options={
                'db_table': 'alertas_sanitarias',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
